### ISSUE TITLE
Remove Dataprovider from data/ remove ASE dependency

### ISSUE THREAD

**Issue by andersx** [qmlcode/qml#106]
As said in title. These are superseeded by the QMLearn interface.

This will also remove the dependency on ASE, as far as I can see.

Any downsides to this @larsbratholm ?

**Comment by larsbratholm** [comment]
The ASE interface might be nice to have in the future for other filetypes
than XYZ. But they should inherit from the Data class. Until someone
actually adds something that depends on ASE, we should indeed remove the
dependency.

**Comment by andersx** [comment]
I'll make a PR to remove the outdated dataprovider and (for now) remove ase then!

**Comment by andersx** [comment]
Closing this now that PR #108 is accepted!
