### ISSUE TITLE
`numpy.distutils` dependency 

### ISSUE THREAD

**Issue by vivinvinod** [qmlcode/qml#152]
`numpy.distutils` is deprecated as of np 1.23.0 and removed from python >= 3.12; qmlcode in its current version still has this dependency.

**Comment by charnley** [comment]
@vivinvinod, You are correct. We are currently moving the main code over to https://github.com/qmlcode/qmllib to have a smaller library code (all the nice Fortran) to build on top. I need to fix a minor bug I introduced before publishing a 1.0.

**Comment by charnley** [comment]
Please note that further development for the QML package is now happening on the [qmlcode/qmllib](https://github.com/qmlcode/qmllib) repository. ``qmllib`` is a port of the QML's Fortran core functionality with fewer dependencies. We encourage you to open any future issues or pull requests there.
