### ISSUE TITLE
FCHL python/fortran interface bug

### ISSUE THREAD

**Issue by larsbratholm** [qmlcode/qml#86]
The same fortran function is called two different places in the code, using different parameters.

https://github.com/qmlcode/qml/blob/develop/qml/fchl/fchl_scalar_kernels.py#L132

https://github.com/qmlcode/qml/blob/develop/qml/fchl/fchl_kernels.py#L148

One has a verbose flag and one does not, so one of them must be wrong?

**Comment by larsbratholm** [comment]
The fchl_kernels file does not seem to be used anywhere, so I assume that it's legacy code and can be removed?

**Comment by andersx** [comment]
Yeah, that one should have been removed!
