### ISSUE TITLE
Dataset downloaders

### ISSUE THREAD

**Issue by eickenberg** [qmlcode/qml#97]
Hi everybody,

I'm Michael Eickenberg. I came to visit Basel in December 2016 to work with Samuel on the scattering transform for electronic densities. In the context of this, I started an open source software package in which I wanted to gather all sorts of machine learning algorithms for molecule property estimation. Alas it only got to having some **nice dataset downloaders** (the scattering transform itself, which I wanted to also put in this package, is now being rolled out in a different package - let me know if anybody is interested in alpha-testing it).

Unfortunately, I don't think `CheML` is ever going to rise to Quantum Chemistry Machine Learning Glory, since I don't have time to work on it. So please feel free to use anything useful you find in `CheML` for this package. For example, https://github.com/CheML/CheML/blob/master/cheml/datasets.py has mechanisms for loading datasets and downloading them if they are not present. This is very convenient for showing off examples, because it abstracts away all the data procuration process.

Michael

**Comment by larsbratholm** [comment]
We have something in the works as well, but we'll have a look at your code. Thanks for the offer.
